# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: default
  connection: ssh
  gather_facts: yes
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - "vars.yml"
  roles:
    - geerlingguy.firewall
    - java_role
    - apolloclark.elasticsearch
