# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# geerlingguy/firewall
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "2181" # Zookeeper
  - "5044" # Logstash
  - "5601" # Kibana
  - "9092" # Kafka
  - "9200" # Elasticsearch
  - "9300" # Elasticsearch

# apolloclark/java_role
java_implementation: openjdk
java_open_jdk_version: "11.x"



# apolloclark/elasticsearch
elasticsearch:
  version: "7.3.0"
  install_only: true
  skip_restart: true
  skip_start: true
  install_plugins: []
